specVersion: 1.0.0
name: testnet-subql-debionetwork
version: 0.0.4
runner:
  node:
    name: "@subql/node"
    version: ">=1.0.0"
  query:
    name: "@subql/query"
    version: "*"
description: This project can be use as a starting po...
repository: https://github.com/octopus-appchains/testnet-subql-debionetwork.git
schema:
  file: ./schema.graphql
network:
  endpoint: >-
    wss://gateway.testnet.octopus.network/debionetwork/554976cbb180f676f188abe14d63ca24
  genesisHash: "0xc15da258748903f5341b1cfb0d9f3afa7ed0bfc59be5e1185b6e303277b5237a"
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
